#!/usr/bin/env bash
# One-shot setup for a fresh Debian 12 GCE VM.
#
# Usage (from your laptop):
#
#   gcloud compute ssh instance-20260416-224642 --zone=us-central1-a --command="bash -s" <<'REMOTE'
#     curl -sSL https://raw.githubusercontent.com/DSC-Lewis/ccs-planner-agent/main/deploy/bootstrap.sh | bash -s -- <ADMIN_KEY>
#   REMOTE
#
# Or SSH in manually then:
#
#   sudo apt-get install -y git && git clone https://github.com/DSC-Lewis/ccs-planner-agent.git
#   bash ccs-planner-agent/deploy/bootstrap.sh <ADMIN_KEY>
set -euo pipefail

ADMIN_KEY="${1:-}"
if [[ -z "$ADMIN_KEY" ]]; then
    echo "Usage: $0 <CCS_ADMIN_KEY>" >&2
    exit 2
fi

REPO_URL="${CCS_REPO_URL:-https://github.com/DSC-Lewis/ccs-planner-agent.git}"
BRANCH="${CCS_BRANCH:-main}"
APP_DIR="${CCS_APP_DIR:-/opt/ccs-planner-agent}"
DATA_DIR="${CCS_DATA_DIR:-/opt/ccs-planner-agent/data}"
PORT="${CCS_PORT:-8000}"

say() { printf '\n\033[1;34m==> %s\033[0m\n' "$1"; }

# ----------------------------------------------------------------------------
# 1. Install Docker Engine + compose plugin
# ----------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
    say "Installing Docker"
    sudo apt-get update -qq
    sudo apt-get install -y -qq ca-certificates curl git gnupg
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg \
        | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/debian bookworm stable" \
        | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
    sudo apt-get update -qq
    sudo apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
        docker-compose-plugin
    sudo systemctl enable --now docker
    # Add the invoking user to the docker group so subsequent runs don't
    # need sudo. They still will on THIS shell until re-login.
    sudo usermod -aG docker "$USER" || true
fi

# ----------------------------------------------------------------------------
# 2. Clone or update the repo
# ----------------------------------------------------------------------------
if [[ ! -d "$APP_DIR/.git" ]]; then
    say "Cloning $REPO_URL @ $BRANCH"
    sudo git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
    sudo chown -R "$USER:$USER" "$APP_DIR"
else
    say "Pulling latest from $BRANCH"
    git -C "$APP_DIR" fetch origin "$BRANCH" --quiet
    git -C "$APP_DIR" checkout "$BRANCH" --quiet
    git -C "$APP_DIR" reset --hard "origin/$BRANCH" --quiet
fi

mkdir -p "$DATA_DIR"

# ----------------------------------------------------------------------------
# 3. Config files: .env + compose override for bind-mount + prod knobs
# ----------------------------------------------------------------------------
say "Writing .env"
cat > "$APP_DIR/.env" <<EOF
CCS_ADMIN_KEY=$ADMIN_KEY
CCS_PORT=$PORT
CCS_DATABASE_PATH=/data/ccs.db
CCS_STORAGE_PATH=/data/storage.json
CCS_RATE_LIMIT=30/60
CCS_SESSION_TTL_SECONDS=604800
EOF
chmod 600 "$APP_DIR/.env"

say "Writing docker-compose.override.yml (bind-mount + env_file)"
cat > "$APP_DIR/docker-compose.override.yml" <<EOF
# Generated by deploy/bootstrap.sh — safe to rerun.
services:
  ccs-agent:
    env_file: .env
    volumes:
      - $DATA_DIR:/data
    # docker-compose.yml also declares a named volume for /data; the bind
    # mount above wins because it comes later in the compose merge order.
EOF

# ----------------------------------------------------------------------------
# 4. Build + run
# ----------------------------------------------------------------------------
say "Building image + launching container"
cd "$APP_DIR"
sudo docker compose up --build -d

# ----------------------------------------------------------------------------
# 5. Smoke test
# ----------------------------------------------------------------------------
say "Waiting for /api/health"
for _ in $(seq 1 30); do
    if curl -sf "http://localhost:$PORT/api/health" >/dev/null 2>&1; then
        break
    fi
    sleep 1
done
curl -sf "http://localhost:$PORT/api/health" | python3 -m json.tool

EXT_IP="$(curl -s -H 'Metadata-Flavor: Google' \
    http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip || true)"

cat <<EOF

✅ CCS Planner deployed.

   Internal :  http://localhost:$PORT
   External :  http://$EXT_IP:$PORT
   Admin key:  (the one you passed to bootstrap.sh)

   Next:
   1. On your laptop, make sure the firewall rule is open:
      ./deploy/firewall.sh
   2. Open http://$EXT_IP:$PORT in a browser.
   3. Log in with your admin key.
EOF
